### ISSUE TITLE
train.py new_model_rollout_steps

### ISSUE THREAD

**Issue by alpc91** [x35f/model_based_rl#2]
line108是不是应该加上model_rollout_steps = new_model_rollout_steps？
如果需要加上，加上之后mbpo性能是提升还是下降？

**Comment by x35f** [comment]
嗨喽。
是的，应该加上，，感谢指出bug！
正在测试影响的环境（Ant, Hopper和Humanoid），目前[主目录](https://github.com/x35f/unstable_baselines)的mbpo性能是rollout step都是1的情况，结果预计2-3天后更新结果,会通知您。

**Comment by x35f** [comment]
不好意思最近机器资源比较紧张。
有两个修改的点，一是rollout step，第二个是model rollout的时候策略从deterministic改成了stochastic。
现在基本所有环境都有小幅性能提升，结果已update至主目录readme中的性能图。
感谢反馈bug。

**Comment by alpc91** [comment]
👍
